const CONSTANTS = {
    CIRCLE_NOT_SELECTED_COLOR: "#EEEEEE",
    SELECTED_CIRCLE_COLOR: "#232c50",
    CORRECT_ANSWER_COLOR: "#48a64c",
    WRONG_ANSWER_COLOR: "#dc5044"
}

export default CONSTANTS;
